services:
  logging-whatsapp-bot-service:
    container_name: logging-whatsapp-bot-service
    build: .
    ports:
      - "2000:3000" # Port for Gampang
      - "2001:4000" # Port for API
    env_file:
      - .env
    healthcheck:
      test: ["curl", "http://localhost:4000/health"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 10s
    volumes:
      - logging-whatsapp-bot-sessions:/app/whatsapp_sessions
      - logging-whatsapp-bot-medias:/app/whatsapp_storages

volumes:
  logging-whatsapp-bot-sessions:
  logging-whatsapp-bot-medias: